version: 2.1
jobs:
  build:
    docker:
      - image: node:14.14
    working_directory: ~/repo
    steps:
        - checkout
        - restore_cache:
            keys: 
              - dep-{{ checksum "package.json" }}
              - dep-
        - run:
            name: Install Node Modules
            command: yarn

        - save_cache:
            paths:
              - node_modules
            key: dep-{{ checksum "package.json" }}

        - run:
            name: ESLint check
            command: yarn run lint
            when: on_success

        - run:
            name: Run Jest tests
            command: yarn run test --runInBand
            when: on_success
            no_output_timeout: 20m
